language: objective-c
xcode_workspace: PWProgressView.xcworkspace
xcode_scheme: PWProgressView
xcode_sdk: iphonesimulator
before_install:
  - gem install cocoapods --no-document
  - cd Example\ Project